const fs = require('fs');
const path = require('path');
const https = require('https');

// Apufunktio urlin slug-muunnokselle (sama kuin yrityskorteissa)
function slugify(text) {
    if (!text) return "";
    return text.toString().toLowerCase().trim()
        .replace(/\s+/g, '-')
        .replace(/[\u00e4\u00c4\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5]/g, 'a')
        .replace(/[\u00f6\u00d6\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8]/g, 'o')
        .replace(/[\u00e5\u00c5]/g, 'a')
        .replace(/[^\w-]/g, '')
        .replace(/--+/g, '-')
        .replace(/^-+/, '')
        .replace(/-+$/, '');
}

async function generateSitemap() {
    console.log('--- Generating sitemap.xml + sitemap-mediazoo.xml ---');

    const baseUrl = 'https://laukaainfo.fi/';
    const currentDate = new Date().toISOString().split('T')[0] + 'T00:00:00+00:00';
    
    // 1. Staattiset pääsivut
    const staticPages = [
        'index.html',
        'palvelun-esittely.html',
        'ilmoittaudu.html',
        'kauppa.html',
        'lisaa-yritys.html',
        'laukaa.html',
        'leppavesi.html',
        'lievestuore.html',
        'vehnia.html',
        'vihtavuori.html',
        'ajankohtaista.html',
        'asiahaku.html',
        'kohdekartta.html',
        'tarinakartta.html',
        'muistokartta.html',
        'kadonneet.html',
        'ilmoitukset.html',
        'verkostokartta.html',
        'pikahaku.html',
        'laukaan-ravintolat.html',
        'laukaan-autohuollot.html',
        'laukaan-parturit-ja-kauneus.html',
        'tietoa-paikasta.html',
        'laatu.html',
        'tietosuoja.html',
        'maksuehto.html'
    ];

    // Palveluiden ja reittien id:t (näitä voi laajentaa tarvittaessa)
    const dynamicPages = [
        'pikahaku.html?id=vuokrauspalvelut',
        'palvelu.html?id=haat',
        'palvelu.html?id=yritysjuhlat',
        'palvelu.html?id=yritystilaisuudet',
        'palvelu.html?id=syntymapaivat',
        'palvelu.html?id=muutto',
        'palvelu.html?id=remontti',
        'palvelu.html?id=mokkipalvelut',
        'palvelu.html?id=hautajaiset',
        'palvelu.html?id=yrityksen-perustaminen',
        'palvelu.html?id=yrityksen-kehittaminen',
        'palvelu.html?id=vakituinen-palvelukumppani',
        'palvelu.html?id=kiinteistopalvelut',
        'palvelu.html?id=paivystavat-palvelut',
        'palvelu.html?id=terveys-ja-hyvinvointi',
        'palvelu.html?id=liikunta-ja-vapaaaika',
        'palvelu.html?id=elaimet',
        'palvelu.html?id=lapset-ja-perhe',
        'palvelu.html?id=autohuollot'
    ];

    // ── sitemap.xml: vain laukaainfo.fi URL:it ──────────────────────────────────
    let xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<!-- Generated by LaukaaInfo Build Script: laukaainfo.fi -->

<url>
  <loc>${baseUrl}</loc>
  <lastmod>${currentDate}</lastmod>
  <priority>1.00</priority>
</url>
`;

    // ── sitemap-mediazoo.xml: vain www.mediazoo.fi URL:it ───────────────────────
    const mediazooBase = 'https://www.mediazoo.fi/laukaainfo-web/';
    let xml2 = `<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<!-- Generated by LaukaaInfo Build Script: www.mediazoo.fi -->

`;

    // Lisätään staattiset sivut
    staticPages.forEach(page => {
        xml += `<url>
  <loc>${baseUrl}${page}</loc>
  <lastmod>${currentDate}</lastmod>
  <priority>0.80</priority>
</url>\n`;
    });

    // Lisätään dynaamiset palvelusivut
    dynamicPages.forEach(page => {
        // Encode ampersands just in case
        const safePage = page.replace(/&/g, '&amp;');
        xml += `<url>
  <loc>${baseUrl}${safePage}</loc>
  <lastmod>${currentDate}</lastmod>
  <priority>0.80</priority>
</url>\n`;
    });

    // 2. Haetaan Premium-yritykset ja lisätään ne sitemapiin
    const companiesFile = path.join(__dirname, 'companies_data.json');
    if (fs.existsSync(companiesFile)) {
        try {
            let rawJson = fs.readFileSync(companiesFile, 'utf8');
            if (rawJson.charCodeAt(0) === 0xFEFF) rawJson = rawJson.slice(1);
            const data = JSON.parse(rawJson);
            const companies = data.results || [];
            
            let premiumCount = 0;
            companies.forEach(company => {
                const isPremium = company.tyyppi === 'maksu' || company.tyyppi === 'paid';
                if (isPremium && company.nimi) {
                    const slug = slugify(company.nimi);
                    xml += `<url>
  <loc>${baseUrl}yritys/${slug}.html</loc>
  <lastmod>${currentDate}</lastmod>
  <priority>0.90</priority>
</url>\n`;
                    premiumCount++;
                }
            });
            console.log(`✓ Lisätty ${premiumCount} premium-yritystä sitemapiin.`);
        } catch (e) {
            console.error('Virhe companies_data.json lukemisessa:', e.message);
        }
    }

    // 3. Haetaan Place ID:t Supabasesta → mediazoo-sitemapiin place.php -URL:it
    // HUOM: Nämä URL:it ovat www.mediazoo.fi -domainilla, joten ne kuuluvat xml2:een.
    // Vaihe 2 (myöhemmin): build.js generoi staattiset sivut laukaainfo.fi/paikka/... -rakenteeseen.
    const ssrBase = mediazooBase;
    const supabaseUrl = 'https://duxluwyqxvbmkkjzuzkz.supabase.co';
    const supabaseKey = 'sb_publishable_HgfWyipuSO7gvsVUR1smNQ_aXox2OPu';

    try {
        const placesData = await fetchSupabase(
            supabaseUrl, supabaseKey,
            '/rest/v1/places?select=place_id,name&status=eq.ACTIVE&limit=500'
        );

        let placeCount = 0;
        if (Array.isArray(placesData)) {
            placesData.forEach(place => {
                if (!place.place_id) return;
                // Vain SSR PHP-sivu – yksi URL per paikka – xml2 (mediazoo.fi)
                xml2 += `<url>
  <loc>${ssrBase}place.php?id=${encodeURIComponent(place.place_id)}</loc>
  <lastmod>${currentDate}</lastmod>
  <priority>0.80</priority>
</url>\n`;
                placeCount++;
            });
        }
        console.log(`✓ Lisätty ${placeCount} SSR place.php -kohdesivua mediazoo-sitemapiin (yksi URL per paikka).`);
    } catch (e) {
        console.warn('Varoitus: Supabase place-haku epäonnistui, käytetään fallback karttakohteet_raw.json:', e.message);
        // Fallback: OSM-datasta nimimuotoiset URL:it
        const karttaFile = path.join(__dirname, 'karttakohteet_raw.json');
        if (fs.existsSync(karttaFile)) {
            try {
                const rawJson = fs.readFileSync(karttaFile, 'utf8');
                const data = JSON.parse(rawJson);
                const features = data.features || [];
                const addedNames = new Set();
                features.forEach(feature => {
                    const name = feature.properties && feature.properties.name;
                    if (name && !addedNames.has(name)) {
                        addedNames.add(name);
                        const formattedName = encodeURIComponent(name.trim().replace(/\s+/g, '_'));
                        xml += `<url>
  <loc>${baseUrl}tietoa-paikasta.html?name=${formattedName}</loc>
  <lastmod>${currentDate}</lastmod>
  <priority>0.60</priority>
</url>\n`;
                    }
                });
                console.log(`✓ Fallback: Lisätty ${addedNames.size} kohdesivua nimilinkeillä.`);
            } catch (err) {
                console.error('Virhe karttakohteet_raw.json lukemisessa:', err.message);
            }
        }
    }

    // 4. Lisätään teema-sivut → mediazoo-sitemapiin (teema.php on www.mediazoo.fi -domainilla)
    const themeFile = path.join(__dirname, 'theme_taxonomy.json');
    if (fs.existsSync(themeFile)) {
        try {
            let rawTax = fs.readFileSync(themeFile, 'utf8');
            if (rawTax.charCodeAt(0) === 0xFEFF) rawTax = rawTax.slice(1);
            const taxonomy = JSON.parse(rawTax);
            let themeCount = 0;

            const addThemeUrl = (tagId) => {
                if (!tagId) return;
                xml2 += `<url>
  <loc>${mediazooBase}teema.php?tag=${encodeURIComponent(tagId)}</loc>
  <lastmod>${currentDate}</lastmod>
  <priority>0.70</priority>
</url>\n`;
                themeCount++;
            };

            // Pääryhmät
            (taxonomy.main_groups || []).forEach(main => {
                addThemeUrl(main.id);
                (main.groups || []).forEach(group => {
                    addThemeUrl(group.id);
                    (group.tags || []).forEach(tag => addThemeUrl(tag.id));
                });
            });
            // Kohderyhmät, sesongit, ominaisuudet
            ['target_groups', 'seasons', 'features'].forEach(section => {
                (taxonomy[section] || []).forEach(item => addThemeUrl(item.id));
            });

            console.log(`✓ Lisätty ${themeCount} teema.php -URL:ia sitemapiin.`);
        } catch (e) {
            console.error('Virhe theme_taxonomy.json lukemisessa:', e.message);
        }
    }

    xml  += `\n</urlset>`;
    xml2 += `\n</urlset>`;

    // ── Kirjoitetaan sitemap.xml (laukaainfo.fi) projektin juureen ───────────────
    const outputPath = path.join(__dirname, 'sitemap.xml');
    fs.writeFileSync(outputPath, xml, 'utf8');
    console.log(`✓ sitemap.xml generoitu → laukaainfo.fi (${1 + staticPages.length + dynamicPages.length} perussivua + yritykset).`);
    console.log(`  → Lähetä tämä Search Consolessa propertyyn: https://laukaainfo.fi/`);

    // ── Kirjoitetaan sitemap-mediazoo.xml (www.mediazoo.fi) laukaainfo-web/-kansioon ─
    const mediazooSitemapPath = path.join(__dirname, 'laukaainfo-web', 'sitemap-mediazoo.xml');
    fs.writeFileSync(mediazooSitemapPath, xml2, 'utf8');
    console.log(`✓ sitemap-mediazoo.xml generoitu → www.mediazoo.fi (place.php + teema.php URL:it).`);
    console.log(`  → Kopioi MediaZoolle: mediazoo.fi/laukaainfo-web/sitemap-mediazoo.xml`);
    console.log(`  → Lähetä Search Consolessa propertyyn: https://www.mediazoo.fi/`);
}

/**
 * Hakee dataa Supabase REST API:sta (palauttaa Promisen).
 */
function fetchSupabase(baseUrl, apiKey, path) {
    return new Promise((resolve, reject) => {
        const options = {
            hostname: new URL(baseUrl).hostname,
            path: path,
            method: 'GET',
            headers: {
                'apikey': apiKey,
                'Authorization': 'Bearer ' + apiKey,
                'Accept': 'application/json'
            }
        };
        const req = https.request(options, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                try {
                    resolve(JSON.parse(data));
                } catch (e) {
                    reject(new Error('JSON parse error: ' + e.message));
                }
            });
        });
        req.on('error', reject);
        req.setTimeout(8000, () => { req.destroy(); reject(new Error('Timeout')); });
        req.end();
    });
}

if (require.main === module) {
    generateSitemap().catch(e => console.error('Sitemap generointi epäonnistui:', e));
}

module.exports = { generateSitemap };
