const fs = require('fs');
const path = require('path');

// Apufunktio urlin slug-muunnokselle (sama kuin yrityskorteissa)
function slugify(text) {
    if (!text) return "";
    return text.toString().toLowerCase().trim()
        .replace(/\s+/g, '-')
        .replace(/[\u00e4\u00c4\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5]/g, 'a')
        .replace(/[\u00f6\u00d6\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8]/g, 'o')
        .replace(/[\u00e5\u00c5]/g, 'a')
        .replace(/[^\w-]/g, '')
        .replace(/--+/g, '-')
        .replace(/^-+/, '')
        .replace(/-+$/, '');
}

function generateSitemap() {
    console.log('--- Generating sitemap.xml ---');

    const baseUrl = 'https://laukaainfo.fi/';
    const currentDate = new Date().toISOString().split('T')[0] + 'T00:00:00+00:00';
    
    // 1. Staattiset pääsivut
    const staticPages = [
        'index.html',
        'palvelun-esittely.html',
        'ilmoittaudu.html',
        'kauppa.html',
        'lisaa-yritys.html',
        'laukaa.html',
        'leppavesi.html',
        'lievestuore.html',
        'vehnia.html',
        'vihtavuori.html',
        'ajankohtaista.html',
        'asiahaku.html',
        'kohdekartta.html',
        'tarinakartta.html',
        'muistokartta.html',
        'kadonneet.html',
        'ilmoitukset.html',
        'verkostokartta.html',
        'pikahaku.html',
        'laukaan-ravintolat.html',
        'laukaan-autohuollot.html',
        'laukaan-parturit-ja-kauneus.html',
        'tietosuoja.html',
        'maksuehto.html'
    ];

    // Palveluiden ja reittien id:t (näitä voi laajentaa tarvittaessa)
    const dynamicPages = [
        'pikahaku.html?id=vuokrauspalvelut',
        'palvelu.html?id=haat',
        'palvelu.html?id=yritysjuhlat',
        'palvelu.html?id=yritystilaisuudet',
        'palvelu.html?id=syntymapaivat',
        'palvelu.html?id=muutto',
        'palvelu.html?id=remontti',
        'palvelu.html?id=mokkipalvelut',
        'palvelu.html?id=hautajaiset',
        'palvelu.html?id=yrityksen-perustaminen',
        'palvelu.html?id=yrityksen-kehittaminen',
        'palvelu.html?id=vakituinen-palvelukumppani',
        'palvelu.html?id=kiinteistopalvelut',
        'palvelu.html?id=paivystavat-palvelut',
        'palvelu.html?id=terveys-ja-hyvinvointi',
        'palvelu.html?id=liikunta-ja-vapaaaika',
        'palvelu.html?id=elaimet',
        'palvelu.html?id=lapset-ja-perhe',
        'palvelu.html?id=autohuollot'
    ];

    let xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<!-- Generated by LaukaaInfo Build Script -->

<url>
  <loc>${baseUrl}</loc>
  <lastmod>${currentDate}</lastmod>
  <priority>1.00</priority>
</url>
`;

    // Lisätään staattiset sivut
    staticPages.forEach(page => {
        xml += `<url>
  <loc>${baseUrl}${page}</loc>
  <lastmod>${currentDate}</lastmod>
  <priority>0.80</priority>
</url>\n`;
    });

    // Lisätään dynaamiset palvelusivut
    dynamicPages.forEach(page => {
        // Encode ampersands just in case
        const safePage = page.replace(/&/g, '&amp;');
        xml += `<url>
  <loc>${baseUrl}${safePage}</loc>
  <lastmod>${currentDate}</lastmod>
  <priority>0.80</priority>
</url>\n`;
    });

    // 2. Haetaan Premium-yritykset ja lisätään ne sitemapiin
    const companiesFile = path.join(__dirname, 'companies_data.json');
    if (fs.existsSync(companiesFile)) {
        try {
            let rawJson = fs.readFileSync(companiesFile, 'utf8');
            if (rawJson.charCodeAt(0) === 0xFEFF) rawJson = rawJson.slice(1);
            const data = JSON.parse(rawJson);
            const companies = data.results || [];
            
            let premiumCount = 0;
            companies.forEach(company => {
                const isPremium = company.tyyppi === 'maksu' || company.tyyppi === 'paid';
                if (isPremium && company.nimi) {
                    const slug = slugify(company.nimi);
                    xml += `<url>
  <loc>${baseUrl}yritys/${slug}.html</loc>
  <lastmod>${currentDate}</lastmod>
  <priority>0.90</priority>
</url>\n`;
                    premiumCount++;
                }
            });
            console.log(`✓ Lisätty ${premiumCount} premium-yritystä sitemapiin.`);
        } catch (e) {
            console.error('Virhe companies_data.json lukemisessa:', e.message);
        }
    }

    xml += `\n</urlset>`;

    // Kirjoitetaan sitemap root-kansioon (se kopioidaan dist-kansioon myöhemmin)
    const outputPath = path.join(__dirname, 'sitemap.xml');
    fs.writeFileSync(outputPath, xml, 'utf8');
    console.log(`✓ sitemap.xml generoitu (Yhteensä: ${1 + staticPages.length + dynamicPages.length} perussivua + yritykset).`);
}

if (require.main === module) {
    generateSitemap();
}

module.exports = { generateSitemap };
