const fs = require('fs');
let code = fs.readFileSync('needs_config.js', 'utf8');

const intentMapping = {
    "OPT_MOVE_SERVICE_FULL": ["MOVE_FULL"],
    "OPT_MOVE_TRANSPORT_ONLY": ["MOVE_TRANSPORT"],
    "OPT_MOVE_STORAGE": ["MOVE_STORAGE"],
    "OPT_MOVE_CLEANING": ["MOVE_CLEANING"],
    "OPT_MOVE_ELECTRICITY": ["MOVE_ELECTRICITY"],
    "OPT_MOVE_RENO_SMALL": ["MOVE_RENO"],

    "OPT_RENO_BATHROOM": ["RENO_BATHROOM"],
    "OPT_RENO_KITCHEN": ["RENO_KITCHEN"],
    "OPT_RENO_SURFACE": ["RENO_SURFACE"],
    "OPT_RENO_NEW_BUILD": ["RENO_NEW"],
    "OPT_RENO_PRO_BUILDER": ["RENO_BUILDER"],
    "OPT_RENO_PRO_ELECTRICIAN": ["RENO_ELECTRICIAN"],
    "OPT_RENO_PRO_PLUMBER": ["RENO_PLUMBER"],
    "OPT_RENO_PRO_PAINTER": ["RENO_PAINTER"],
    "OPT_RENO_PRO_CARPENTER": ["RENO_CARPENTER"],
    "OPT_RENO_PRO_DESIGNER": ["RENO_DESIGNER"],
    "OPT_RENO_MAT_HARDWARE": ["RENO_HARDWARE"],
    "OPT_RENO_MAT_RENTAL": ["RENO_RENTAL"],
    "OPT_RENO_MAT_INTERIOR": ["RENO_INTERIOR"],

    "OPT_COTTAGE_CARE": ["COTTAGE_CARE"],
    "OPT_COTTAGE_CLEAN": ["COTTAGE_CLEANING"],
    "OPT_COTTAGE_FIREWOOD_BASE": ["COTTAGE_FIREWOOD"],
    "OPT_COTTAGE_RENO": ["COTTAGE_RENO"],
    "OPT_COTTAGE_MAINTENANCE": ["COTTAGE_MAINTENANCE"],
    "OPT_COTTAGE_SWEEP": ["COTTAGE_SWEEP"],
    "OPT_COTTAGE_FIREWOOD": ["COTTAGE_FIREWOOD"],
    "OPT_COTTAGE_DOCK": ["COTTAGE_DOCK"],
    "OPT_COTTAGE_YARD": ["COTTAGE_YARD"],
    "OPT_COTTAGE_MACHINE": ["COTTAGE_MACHINE"],
    "OPT_COTTAGE_TRANSPORT": ["BIZ_TRANSPORT"],

    "OPT_HOUSING_MAINTENANCE": ["PROP_MAINTENANCE"],
    "OPT_HOUSING_MANAGEMENT": ["PROP_MANAGEMENT"],
    "OPT_HOUSING_RENO": ["PROP_RENO"],
    "OPT_HOUSING_CLEAN": ["PROP_CLEANING"],
    "OPT_HOUSING_YARD": ["PROP_YARD"],
    "OPT_HOUSING_MANAGEMENT_ADMIN": ["PROP_MANAGEMENT"],
    "OPT_HOUSING_ACCOUNTING": ["PROP_ACCOUNTING"],
    "OPT_HOUSING_LEGAL": ["PROP_LEGAL"],

    "OPT_FUNERAL_ARRANGEMENTS": ["FUNERAL_ARRANGEMENTS"],
    "OPT_FUNERAL_MEMORIAL": ["FUNERAL_MEMORIAL"],
    "OPT_FUNERAL_LEGAL": ["FUNERAL_LEGAL"],
    "OPT_FUNERAL_SERVICE": ["FUNERAL_SERVICE"],
    "OPT_FUNERAL_STONES": ["FUNERAL_STONES"],
    "OPT_FUNERAL_CATERING": ["BIZ_CATERING"],
    "OPT_FUNERAL_FLOWERS": ["BIZ_FLORIST"],
    "OPT_FUNERAL_TRANSPORT": ["BIZ_TRANSPORT"],
    "OPT_FUNERAL_LEGAL_INVENTORY": ["FUNERAL_INVENTORY"],
    "OPT_FUNERAL_LEGAL_WILL": ["FUNERAL_WILL"],
    "OPT_FUNERAL_LEGAL_ADVICE": ["FUNERAL_ADVICE"],
    "OPT_FUNERAL_MEM_VIDEO": ["MEDIA_VIDEO"],
    "OPT_FUNERAL_MEM_PHOTO": ["MEDIA_PHOTO"],
    "OPT_FUNERAL_MEM_DIGI": ["MEDIA_DIGITIZATION"],

    "OPT_STARTUP_IDEA": ["STARTUP_IDEA"],
    "OPT_STARTUP_REG": ["STARTUP_REG"],
    "OPT_STARTUP_MARKETING": ["STARTUP_MARKETING"],
    "OPT_STARTUP_ADVISORY": ["STARTUP_ADVISORY"],
    "OPT_STARTUP_ACCOUNTING": ["STARTUP_ACCOUNTING"],
    "OPT_STARTUP_INSURANCE": ["STARTUP_INSURANCE"],
    "OPT_STARTUP_LEGAL": ["STARTUP_LEGAL"],
    "OPT_STARTUP_WEB": ["STARTUP_WEB"],
    "OPT_STARTUP_BRAND": ["STARTUP_BRAND"],
    "OPT_STARTUP_ADS": ["STARTUP_ADS"],
    "OPT_STARTUP_PHOTO": ["MEDIA_PHOTO"],

    "OPT_GROWTH_MARKETING": ["GROWTH_MARKETING"],
    "OPT_GROWTH_STAFF": ["GROWTH_STAFF"],
    "OPT_GROWTH_CONSULT": ["GROWTH_CONSULT"],
    "OPT_GROWTH_SEO": ["GROWTH_SEO"],
    "OPT_GROWTH_SOCIAL": ["GROWTH_SOCIAL"],
    "OPT_GROWTH_ECOMMERCE": ["GROWTH_ECOMMERCE"],
    "OPT_GROWTH_VIDEO": ["MEDIA_VIDEO"],
    "OPT_GROWTH_RECRUIT": ["GROWTH_RECRUIT"],
    "OPT_GROWTH_TRAINING": ["GROWTH_TRAINING"],
    "OPT_GROWTH_MANAGEMENT": ["GROWTH_CONSULT"],

    "OPT_PARTNER_IT": ["PARTNER_IT"],
    "OPT_PARTNER_CLEAN": ["PARTNER_CLEAN"],
    "OPT_PARTNER_ACCOUNTING": ["PARTNER_ACCOUNTING"],
    "OPT_PARTNER_MARKETING": ["PARTNER_MARKETING"],

    "OPT_EMERGENCY_HVAC": ["EMERGENCY_HVAC"],
    "OPT_EMERGENCY_ELECTRIC": ["EMERGENCY_ELECTRIC"],
    "OPT_EMERGENCY_TOWING": ["EMERGENCY_TOWING"],
    "OPT_EMERGENCY_LOCKSMITH": ["EMERGENCY_LOCKSMITH"],

    "OPT_WELLBEING_MASSAGE": ["WELLBEING_MASSAGE"],
    "OPT_WELLBEING_BEAUTY": ["WELLBEING_BEAUTY"],
    "OPT_WELLBEING_HEALTH": ["WELLBEING_HEALTH"],
    "OPT_WELLBEING_THERAPY": ["WELLBEING_THERAPY"],
    "OPT_WELLBEING_CARE": ["WELLBEING_CARE"],

    "OPT_PETS_VET": ["PETS_VET"],
    "OPT_PETS_SUPPLIES": ["PETS_SUPPLIES"],
    "OPT_PETS_GROOMING": ["PETS_GROOMING"],
    "OPT_PETS_CARE": ["PETS_CARE"],
    "OPT_PETS_DOG": ["PETS_DOG"],
    "OPT_PETS_CAT": ["PETS_CAT"],
    "OPT_PETS_HORSE": ["PETS_HORSE"],
    "OPT_PETS_SMALL": ["PETS_SMALL"]
};

const regex = /\{\s*"id"\s*:\s*"([^"]+)"\s*,([^}]+)\}/g;
const newCode = code.replace(regex, (match, id, rest) => {
    if (intentMapping[id] && !match.includes('"intent_codes"')) {
        return `{ "id": "${id}",${rest.replace(/\s*$/, '')}, "intent_codes": ${JSON.stringify(intentMapping[id])} }`;
    }
    return match;
});

fs.writeFileSync('needs_config.js', newCode);
console.log('Updated needs_config.js');
