const fs = require('fs');
let c = fs.readFileSync('ilmoittaudu.html', 'utf8');
c = c.replace(/Ã¤/g, 'ä')
     .replace(/Ã„/g, 'Ä')
     .replace(/Ã¶/g, 'ö')
     .replace(/Ã–/g, 'Ö')
     .replace(/â€“/g, '–')
     .replace(/â–¼/g, '▼')
     .replace(/Ã¢Â­Â/g, '⭐')
     .replace(/ðŸš€/g, '🚀')
     .replace(/ðŸ“£/g, '📢')
     .replace(/ðŸ ¢/g, '🏢')
     .replace(/ðŸ“ /g, '📍')
     .replace(/ðŸ”—/g, '🔗')
     .replace(/ðŸ“¢/g, '📣')
     .replace(/ðŸ’»/g, '💻')
     .replace(/ðŸ ¡/g, '🏡')
     .replace(/ðŸ”¨/g, '🔨')
     .replace(/ðŸš—/g, '🚗')
     .replace(/ðŸ‘´/g, '👴')
     .replace(/ðŸŽ‰/g, '🎉')
     .replace(/ðŸŽµ/g, '🎵')
     .replace(/ðŸ”¹/g, '🔹')
     .replace(/ðŸ“Œ/g, '📌')
     .replace(/ðŸ¤ /g, '🤝')
     .replace(/ðŸ‘¥/g, '👥')
     .replace(/â‚¬/g, '€');
fs.writeFileSync('ilmoittaudu.html', c, 'utf8');
